version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: migration-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: migration-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped

volumes:
  redis_data:
  mongodb_data:
